on:
  push:
    branches: [master]
  pull_request:
name: CI
jobs:
  flatpak-tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/andyholmes/flatter/gnome:46
      options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build
        uses: andyholmes/flatter@main
        with:
          files: |
            com.github.tchx84.Flatseal.json
          upload-bundles: true
